### PR TITLE
Support for building manylinux1 wheels

### LINKED ISSUE #557: Publish manylinux wheels for v0.7.1
`pip install JPype1==0.7.1` requires a compiler toolchain.  If manylinux wheels are published, this requirement is eliminated.

### PR DESCRIPTION
**Pull request by Thrameos**
Fixes #557 

This pull request adds scripts to use docker to build manylinux wheels.

### CODE REVIEW

**Comment by marscher** [comment]
Hi, this will greatly simplify things. Is there also a Dockerfile to specify the containers details?

**Comment by Thrameos** [comment]
Yes the dockers are from github manylinux repo.   We can likely build our own if you would like.  

https://github.com/pypa/manylinux

**Comment by marscher** [comment]
On 1/8/20 2:23 PM, Karl Nelson wrote:
> Yes the dockers are from github manylinux repo.   We can likely build our own if you would like.
> 
> https://github.com/pypa/manylinux
> 
We don't need the jdk anymore, do we?

**Comment by Thrameos** [comment]
No building the sdist locally removes that dependency.  Thus could yse manylinux out of box

**Comment by Thrameos** [comment]
We cant actually test then in the docker without java, but we can build them.

**Comment by marscher** [comment]
On 1/8/20 2:28 PM, Karl Nelson wrote:
> No building the sdist locally removes that dependency.  Thus could yse manylinux out of box
> 
pretty cool :) Thanks

**Comment by marscher** [comment]
On 1/8/20 2:30 PM, Karl Nelson wrote:
> We cant actually test then in the docker without java, but we can build them.
> 
testing has been done before releasing, so the built version should be fine.

**Comment by Thrameos** [comment]
Do you know how to push the results to pypi?  I pushed them to github release for now.

**Comment by marscher** [comment]
I can upload them.

**Comment by marscher** [comment]
I guess we also want to have builds for Python 3.8

**Comment by Thrameos** [comment]
Okay i can add them to the build but it wont be until evening PST.

**Comment by marscher** [comment]
400 Binary wheel 'JPype1-0.7.1-cp35-cp35m-linux_x86_64.whl' has an unsupported platform tag 'linux_x86_64'

I think it should be manylinux. Somethings wrong. I guess these need to be converted somehow.

**Comment by Thrameos** [comment]
Perhaps we need to add auditwheel repair to the build pattern.

**Comment by Thrameos** [comment]
There is a manylinux demo on github that i was working from.  Perhaps i missed a step.

**Comment by Thrameos** [comment]
Also possible the no index flag was a requirement.  Will have to investigate further.

**Pull request merged**
