### PR TITLE
fix compatibility of jpype with setuptools==72.0.0

### PR DESCRIPTION
**Pull request by alexrashed**
## Motivation
With `setuptools==72.0.0`, the test command [was removed](https://github.com/pypa/setuptools/pull/4458) after [being deprecated for a long time](https://github.com/pypa/setuptools/issues/1684).
This completely breaks the installation of any packages using the test command, including JPype.
See https://github.com/pypa/setuptools/issues/4519 for other issue reports.
This PR fixes JPype to be compatible with setuptools 72+ again.
Fixes https://github.com/jpype-project/jpype/issues/1205.

## Changes
- Removes the test alias and command.
- Adjusts a line in the docs
- `setup.py test` was not used in CI anymore, so in terms of usage, this PR only adjusts one line in the docs.

## Testing
Before:
```
$ pip install --upgrade setuptools
$ pip install -e .
Obtaining file:///home/.../Repos/kyuubi/python
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/.../Repos/kyuubi/python/setup.py", line 4, in <module>
          from setuptools.command.test import test as TestCommand
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

With the code in this PR:
```
$ pip install --upgrade setuptools
$ pip install -e .
Obtaining file:///home/.../Repos/jpype
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: packaging in ./.venv/lib/python3.11/site-packages (from JPype1==1.5.0.dev0) (24.1)
Building wheels for collected packages: JPype1
  Building editable for JPype1 (pyproject.toml) ... done
  Created wheel for JPype1: filename=JPype1-1.5.0.dev0-0.editable-cp311-cp311-linux_x86_64.whl size=9998 sha256=4783526b2a6725dfa504b1d71cdc5feaa4d4256319c001c0a97c0809905d2e98
  Stored in directory: /tmp/pip-ephem-wheel-cache-6fkq_j06/wheels/ca/b9/cd/ed1acf12ba47865d19baa6a7e9f7464d25608d983055f6fbf6
Successfully built JPype1
Installing collected packages: JPype1
Successfully installed JPype1-1.5.0.dev0
```

### CODE REVIEW

**Comment by Thrameos** [comment]
@marscher are you around?  There have been a number of items requiring update recently.  If you aren't available for review I will likely have to self review and get the ball rolling towards a release.

**Comment by pelson** [comment]
> If you aren't available for review I will likely have to self review and get the ball rolling towards a release.

I can step up for some review. Particularly on the Python infra side of things. Feel free to ping me.

**Comment by pelson** [comment]
FWIW, I think this PR is good to go as it is.

**Comment by Thrameos** [comment]
Thanks.  I will start merging.   I will also need to finish the patch/kludge for 3.13 before we release.

**Comment by marscher** [comment]
Sorry for being not available for so long. Thanks for the patch. I think this is pretty straight forward.

**Review by marscher — APPROVED** [review]

**Pull request merged**
