### PR TITLE
Improved error reporting when JVM version too old

### LINKED ISSUE #549: better error message for mismatched java versions
Tried to run with old java version, error message was:
```
Traceback (most recent call last):
  File "py/vm250/analysisFromDailyFile.py", line 16, in <module>
    from utilities import startJPype
  File "/Users/labov1/Documents/Simon/PROJECTS/ERNIE/ERNIE.NSDD/software/12_18_ERNIE_VM250/proj-ernie4/py/utilities/startJPype.py", line 65, in <module>
    '-Djava.class.path=%s' % javaClasspath(), convertStrings=False
  File "/Users/labov1/opt/anaconda3/lib/python3.7/site-packages/jpype/_core.py", line 219, in startJVM
    _jpype.startup(jvmpath, tuple(args), ignoreUnrecognized, convertStrings)
jpype._jclass.UnsupportedClassVersionError: org/jpype/classloader/JPypeClassLoader : Unsupported major.minor version 52.0
```
Can you make this less obscure and say that finding java 1.7, needs java 1.8?

### PR DESCRIPTION
**Pull request by Thrameos**
This is a pull request to try to cut down on this common error.

Fixes #549

### CODE REVIEW

**Comment by Thrameos** [comment]
Seems like we need to drop 2.7 from the test matrix.  Appears travis and appveyor have pulled the plug already.

**Comment by Thrameos** [comment]
Actually I am unsure on this.... several times the CI has failed to do Python 2.7 builds but sometimes it works?  Should we just move it to acceptable failures rather than pulling it entirely?

**Comment by Thrameos** [comment]
@marscher Okay I guess this is ready to go.

**Comment by Thrameos** [comment]
@marscher This is freshened and ready to go.

**Comment by marscher** [comment]
Thank you!

**Pull request merged**
