### PR TITLE
Tests for duck typing of primitives.

### PR DESCRIPTION
**Pull request by Thrameos**
Adds a bunch of tests having to do with type conversion.  This is part of the currently out of date duck typing patch for primitives.  Most of these tests fail currently.  I will revise it with the corresponding code, but not until the head catches up because the type conversion code touches code that from the other pulls preventing merging for now.

### CODE REVIEW

**Comment by Thrameos** [comment]
This pull request adds duck typing to all uses of primitive types.  This allows native numpy types as well as user defined types to be treated properly when calling java methods.  Part of it uses the concept of "checkIndexable" to distinguish between integer and floating point types so that we can handle types that define both `__int__` and `__float__`.    With this and the array pull request and the numpy array pull request we are much better able to handle numpy.  

There may be minor side effects that result from the change of order when considering types for conversion, though those changes are outside of our current test bench.   I have a large conversion level api which will handle the cases for objects which will handle java `Instant`/`Path` and python equivalent types.  But that will have to come post 0.7.0.

**Comment by Thrameos** [comment]
Ouch that appveyor CI is really slow!  Most of the 20 minutes is being spent on installing the jdk.  Got to be a faster way to do that.

**Comment by marscher** [comment]
I have fixed this on master I'd guess, so you can just copy it over.

**Comment by Thrameos** [comment]
Okay I will try to pull it over from master.

**Comment by marscher** [comment]
it is just the appyeyor.yaml file

**Pull request merged**
