### PR TITLE
Fix RTD

### PR DESCRIPTION
**Pull request by Thrameos**

### CODE REVIEW

**Comment by marscher** [comment]
jpype imports _jpype, which is not yet mocked, so RTD still fails.

**Comment by marscher** [comment]
```
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 368, in eval_config_file
    execfile_(filename, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/envs/latest/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/checkouts/latest/doc/conf.py", line 25, in <module>
    import jpype
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/checkouts/latest/jpype/__init__.py", line 17, in <module>
    from ._jpackage import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/jpype/checkouts/latest/jpype/_jpackage.py", line 19, in <module>
    import _jpype
ModuleNotFoundError: No module named '_jpype'
```

**Comment by Thrameos** [comment]
Got it.  Will bust my system a bit more so I can replicate it.

**Comment by marscher** [comment]
Hold on for a sec. I think I got this. One evil commit directly to master :P

**Comment by Thrameos** [comment]
Okay I see the problem on my system.  The jpype imports needs to move below the mock, but secondarily the jpype.imports which is needed for doc is dying on a missing resource.

```
$ python3 -m sphinx -b html doc doc/html
Running Sphinx v2.1.2

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\sphinx\config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "C:\ProgramData\Miniconda3\lib\site-packages\sphinx\util\pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "F:\nelson85pl\nelson85\devel\open\jpype\doc\conf.py", line 64, in <module>
    import jpype.imports
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\imports.py", line 412, in <module>
    _jinit.registerJVMInitializer(_initialize)
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jinit.py", line 47, in registerJVMInitializer
    func()
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\imports.py", line 407, in _initialize
    _JMethod = type(_jclass.JClass('java.lang.Class').forName)
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jclass.py", line 130, in __new__
    return _JClassNew(args[0], **kwargs)
  File "F:\nelson85pl\nelson85\devel\open\jpype\jpype\_jclass.py", line 210, in _JClassNew
    if isinstance(arg, _jpype.PyJPClass):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

We just need _jpype.PyJPClass to mock as a type and it will work.

**Comment by marscher** [comment]
> We just need _jpype.PyJPClass to mock as a type and it will work.

Agreed, can you do that?

**Comment by Thrameos** [comment]
Reading the docs now.  My skill with mock is subpar but I can give it a shot.

**Comment by Thrameos** [comment]
Okay I did not manage to get mock to fake a type, but I can stuff a real class in its place and get everything to work.

**Pull request merged**
