### PR TITLE
Update README.rst

### PR DESCRIPTION
**Pull request by krowvin**
This might help someone else using Solaris/Unix and having to compile on two different environments.

### CODE REVIEW

**Comment by pelson** [comment]
Thanks for the suggestion @krowvin. I'm not a maintainer of JPype, but am a user and try to contribute as much as possible to the project.

With regards to this particular MR, I would say that this is extremely niche, and perhaps not even the best solution to the problem, and would rather suggest that this kind of information goes in an issue or even a StackOverflow question which somebody could just Google. Personally, I would therefore suggest that this MR didn't get merged.

With regards to the particular problem, if you really want to build portable JPypes beyond what is available already as a wheel on ``PyPI``, I would suggest building a manylinux based wheel of JPype. If you have docker this is fairly easy. The actual release approach taken in this repo can be found at https://github.com/jpype-project/jpype/blob/master/.azure/scripts/build-wheels.sh, and is basically reproduced with:

```
echo <<EOF > Dockerfile
FROM quay.io/pypa/manylinux2014_x86_64

# We need Java to build JPype
RUN yum install -y java-1.8.0-openjdk-devel
EOF


docker build . -t manylinux2014_x86_64-java-1-8
SRC_DIR=$(pwd)/..
docker run -it -v ${SRC_DIR}:${SRC_DIR} --workdir ${SRC_DIR} manylinux2014_x86_64-java-1-8 \
    /opt/python/cp39-cp39/bin/python -m build ./ --wheel

docker run -it -v ${SRC_DIR}:${SRC_DIR} --workdir ${SRC_DIR} manylinux2014_x86_64-java-1-8 \
    find ./dist -name '*.whl' -exec auditwheel repair {} \;


echo "Wheels in ${SRC_DIR}/wheelhouse"
```

This wheel will be nice and portable, and is installable on manylinux compatible systems.

**Comment by krowvin** [comment]
Thank you for the detailed response. I agree it is far from common.

**Comment by Thrameos** [comment]
The modified file is project/debug/unix/README.rst which is a non-distributed file intended to help people that just can't get JPype to compile at all (usually IBM and Solaris systems with broken compilers/JVMs).  There is a similar one for Windows (again with broken environments).    So I think the contribution is perfectly reasonable given that it is in the last resort help file.   However, it would be a good idea if we add this to place something about the symptoms that lead to the diagnosis.   After a suggestion that says "try this" without telling them a symptom to look for is likely just to get someone to chase a red herring.

**Comment by pelson** [comment]
> The modified file is project/debug/unix/README.rst

Sorry! I totally missed that. Indeed, that changes dramatically my response :smile: :+1: .

**Pull request merged**
