### PR TITLE
Correct bugs in hints system

### PR DESCRIPTION
**Pull request by Thrameos**
Deals with bugs reported in #714.  Throwable had the wrong wrapper type in the class factor.  Adds automatic conversion for List and Iterable, though they may be costly.   This is probably safe for 1.0.2 but if you want me to push it to 1.1 then just set the milestone on the review.

### CODE REVIEW

**Comment by Thrameos** [comment]
@marcher I removed the one problematic converter (though long term we may want to add it back).   The rest seems small enough to be a bug fix.   As this is a minor API with no user impact, I will merge and push in the 1.0.2 if you don't have time to review.

**Comment by marscher** [comment]
Thanks for quickly fixing this.
23h hours to review? Was it that urgent/had security implications?
At least a change log should contain a notice about the fixed bug (which had user implications as far as I noticed).

**Comment by Thrameos** [comment]
Sorry I was going to cut 1.0.2 and wanted to get it included.  It was unfortunately a serious error as although there are not many interfaces that take Throwable it would have given some very strange results as it would have produced an Object rather than a Throwable.  I will be sure to add a note in the log.

**Comment by Thrameos** [comment]
Again sorry if it appeared that I was rushing you on the review.  I was behind in making the release so I was trying to get it going during my window during the morning group check in call, unfortunately I was running late.  I will need to do another patch release in another two weeks if more issues turn up.

**Pull request merged**
