### PR TITLE
Fix the azure pipeline to use a non-deprecated Windows version

### PR DESCRIPTION
**Pull request by pelson**
I'm currently seeing failures in #1039 due to a brownout of the win2016 azure image. This updates the pipeline to use windows 2019 (which requires updating the visual studio version).

See also https://github.com/actions/virtual-environments/issues/4312

I noticed that there is a possibility to test against x64 and x86, but wasn't sure how to enable this. Something that may be interesting for a future MR.

### CODE REVIEW

**Comment by pelson** [comment]
I'm kind of excited by some of the test failures:

```
================================== FAILURES ===================================
______________________ BufferTestCase.testDoubleConvert _______________________

self = <test_buffer.BufferTestCase testMethod=testDoubleConvert>

    @common.unittest.skipUnless(haveNumpy(), "numpy not available")
    def testDoubleConvert(self):
>       self.executeConvert(JArray(JDouble), np.float64)

test\jpypetest\test_buffer.py:160: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
test\jpypetest\test_buffer.py:125: in executeConvert
    self.assertTrue(np.all(np.array(jtype(na), dtype=dtype)
E   AssertionError: False is not true
_______________________ BufferTestCase.testFloatConvert _______________________

self = <test_buffer.BufferTestCase testMethod=testFloatConvert>

    @common.unittest.skipUnless(haveNumpy(), "numpy not available")
    def testFloatConvert(self):
>       self.executeConvert(JArray(JFloat), np.float32)

test\jpypetest\test_buffer.py:156: 

```

These look like precisely the kind of machine dependent failure that I am trying to tackle in #1039.

**Comment by Thrameos** [comment]
Seems like a bunch of deprecation warnings as well.   Perhaps we have to clear them up as well.

**Comment by pelson** [comment]
With some refinement, the test now shows the cause of the issue a bit clearer:

```
______________________ BufferTestCase.testDoubleConvert _______________________

self = <test_buffer.BufferTestCase testMethod=testDoubleConvert>

    @common.unittest.skipUnless(haveNumpy(), "numpy not available")
    def testDoubleConvert(self):
>       self.executeConvert(JArray(JDouble), np.float64)

test\jpypetest\test_buffer.py:189: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_buffer.BufferTestCase testMethod=testDoubleConvert>
jtype = <java class 'double[]'>, dtype = <class 'numpy.float64'>

    def executeConvert(self, jtype, dtype):
    
        n = 100
        na = np.random.randint(0, 1, size=n).astype(bool)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(-2**7, 2**7 - 1, size=n, dtype=np.int8)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    

        na = np.random.randint(0, 2**8 - 1, size=n, dtype=np.uint8)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(-2**15, 2**15 - 1, size=n, dtype=np.int16)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(0, 2**16 - 1, size=n, dtype=np.uint16)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(-2**31, 2**31 - 1, size=n, dtype=np.int32)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(0, 2**32 - 1, size=n, dtype=np.uint32)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(-2**63, 2**63 - 1, size=n, dtype=np.int64)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(0, 2**64 - 1, size=n, dtype=np.uint64)
>       np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 11 / 100 (11%)
E       Max absolute difference: 2048.
E       Max relative difference: 2.1075528e-16
E        x: array([1.710838e+19, 8.347277e+18, 9.717432e+18, 5.238146e+18,
E              3.817785e+18, 1.656521e+19, 1.271839e+19, 4.426652e+18,
E              1.835957e+19, 1.335125e+19, 5.382931e+18, 1.341460e+19,...
E        y: array([1.710838e+19, 8.347277e+18, 9.717432e+18, 5.238146e+18,
E              3.817785e+18, 1.656521e+19, 1.271839e+19, 4.426652e+18,
E              1.835957e+19, 1.335125e+19, 5.382931e+18, 1.341460e+19,...

test\jpypetest\test_buffer.py:146: AssertionError

```

And

```
_______________________ BufferTestCase.testFloatConvert _______________________

self = <test_buffer.BufferTestCase testMethod=testFloatConvert>

    @common.unittest.skipUnless(haveNumpy(), "numpy not available")
    def testFloatConvert(self):
>       self.executeConvert(JArray(JFloat), np.float32)

test\jpypetest\test_buffer.py:185: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_buffer.BufferTestCase testMethod=testFloatConvert>
jtype = <java class 'float[]'>, dtype = <class 'numpy.float32'>

    def executeConvert(self, jtype, dtype):
    
        n = 100
        na = np.random.randint(0, 1, size=n).astype(bool)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(-2**7, 2**7 - 1, size=n, dtype=np.int8)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(0, 2**8 - 1, size=n, dtype=np.uint8)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(-2**15, 2**15 - 1, size=n, dtype=np.int16)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(0, 2**16 - 1, size=n, dtype=np.uint16)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(-2**31, 2**31 - 1, size=n, dtype=np.int32)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(0, 2**32 - 1, size=n, dtype=np.uint32)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(-2**63, 2**63 - 1, size=n, dtype=np.int64)
        np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
    
        na = np.random.randint(0, 2**64 - 1, size=n, dtype=np.uint64)
>       np.testing.assert_array_equal(
            np.array(jtype(na), dtype=dtype),
            np.array(na, dtype=dtype),
        )
E       AssertionError: 
E       Arrays are not equal
E       
E       Mismatched elements: 7 / 100 (7%)
E       Max absolute difference: 1.0995116e+12
E       Max relative difference: 1.09924684e-07
E        x: array([7.819001e+18, 2.240689e+18, 1.198326e+19, 4.609387e+18,
E              7.140427e+18, 1.073009e+19, 1.269285e+19, 1.469904e+19,
E              1.186424e+17, 2.673267e+18, 5.310913e+17, 1.684725e+19,...
E        y: array([7.819001e+18, 2.240689e+18, 1.198326e+19, 4.609387e+18,
E              7.140427e+18, 1.073009e+19, 1.269285e+19, 1.469904e+19,
E              1.186424e+17, 2.673267e+18, 5.310913e+17, 1.684725e+19,...

test\jpypetest\test_buffer.py:146: AssertionError
```

Fundamentally, I think this test is showing that there is a difference between Java's ``uint64 to float/double`` conversion and that of numpy. This is a bit of a surprise, but not entirely implausible. 

Unfortunately this test is not changed/fixed by #1039.

In order to proceed, I think moving to ``assert_arrays_almost_equal`` makes sense, but perhaps @Thrameos has some other ideas?

**Comment by pelson** [comment]
Now I think there is a completely unrelated failure on Windows & Mac:

```
Collecting pyinstaller==4.0
  Downloading pyinstaller-4.0.tar.gz (3.5 MB)
     ---------------------------------------- 3.5/3.5 MB 27.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  Preparing metadata (pyproject.toml) did not run successfully.
  exit code: 1
  
  [42 lines of output]
  Traceback (most recent call last):
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
      main()
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "c:\hostedtoolcache\windows\python\3.8.10\x64\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-lc82mmak\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-lc82mmak\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
      super(_BuildMetaLegacyBackend,
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-lc82mmak\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 75, in <module>
      setup(
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-lc82mmak\overlay\Lib\site-packages\setuptools\__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-lc82mmak\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 122, in setup
      dist.parse_config_files()
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-lc82mmak\overlay\Lib\site-packages\setuptools\dist.py", line 850, in parse_config_files
      setupcfg.parse_configuration(
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-lc82mmak\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 167, in parse_configuration
      meta.parse()
    File "C:\Users\VssAdministrator\AppData\Local\Temp\pip-build-env-lc82mmak\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 446, in parse
```

**Comment by Thrameos** [comment]
@pelson  I have fixed the azure pipeline so I am going to close this one for now.   I fixed the deprecation warnings in a different way.   The names for types were changed to use an underscore where there was a conflict.   Changing "np.bool" to "bool" would have caused a bunch of the tests to become redundant so I made it "np.bool_" which though still redundant (bool==np.bool_) it at least maintains the spirt of the test.   There is a function "np.allclose" which I could fix the remaining conversion tests with so we don't need to implement approximately equals ourselves.   

Some of your changes look useful, but I don't have time to sort the good from the unnecessary currently.   Sorry for not getting to this quickly.

**Comment by Thrameos** [comment]
@pelson  I have fixed the azure pipeline so I am going to close this one for now.   I fixed the deprecation warnings in a different way.   The names for types were changed to use an underscore where there was a conflict.   Changing "np.bool" to "bool" would have caused a bunch of the tests to become redundant so I made it "np.bool_" which though still redundant (bool==np.bool_) it at least maintains the spirt of the test.   There is a function "np.allclose" which I could fix the remaining conversion tests with so we don't need to implement approximately equals ourselves.   

Some of your changes look useful, but I don't have time to sort the good from the unnecessary currently.   Sorry for not getting to this quickly.

**Comment by pelson** [comment]
Thanks. Will pick up some of the good bits and propose them.

**Pull request closed without merging**
