### PR TITLE
Add Python 3.9 to build and test matrix

### PR DESCRIPTION
**Pull request by marscher**
trying to add python-3.9 again

### CODE REVIEW

**Comment by marscher** [comment]
On Windows, Python-3.9 all subrun related tests fail for an empty Queue during setUpClass. @Thrameos do you have an idea whats going on there?

**Comment by marscher** [comment]
https://dev.azure.com/jpype-project/jpype/_build/results?buildId=717&view=logs&j=156bdf7b-70dc-51a2-f964-752e46e62347&t=8ae2d162-6cbc-52e0-5cf7-05eb6651a9df
It seems to me, that the subprocess or spawned process is using another interpreter. Although I forced it to use the same one has the parent process. The thing fails for some DLL symbols not to be found during import of the extension. But only the non-blocking access to the queue reveals it.

**Comment by Thrameos** [comment]
No I haven't tried the subrun path on 3.9 yet.   It is supposed to be a simple pipe pattern that spawns a shell, calls a command through the pipe, and then gets back the result.

If you need to bypass that for now, just have it call ``--fast`` on the test pattern for 3.9.   That option skips subrun and a few of the exotic tests like jedi.   I use it when I am trying to isolate problems quickly and don't want to wait for leak checkers and the like to complete.

**Comment by marscher** [comment]
@Thrameos Azure wants a login from me, only for viewing the pipeline job (failure). If I'm redirected via github there is not forced login. However I cannot login via Github on Azure, did you add me as an collaborator there?

**Comment by Thrameos** [comment]
@marscher give it a try again.  Otherwise you will need to send me a link to the name of the account to add.   It appears that it has multiple registrations for m.scherer.

**Comment by marscher** [comment]
It should be marscher on live.com as well.

**Comment by Thrameos** [comment]
I don't see any registrations for marscher for live in their directory search.  Did you manage to log in using fu-berlin credentials?   You should have administrative access there and can add another account as an admin or a build admin as needed through it.

I have similar issues with their login system.   When I try to login with github it fails because my account was already tied to my organizations login at Microsoft.   This forces me to have to VPN in to my organization and go through their sign on process.  But once I cached the credentials it appears to go through without that for future.   I just have to go through that procedure when I login in from a new machine.

**Comment by marscher** [comment]
On 11/10/20 8:01 PM, Karl Nelson wrote:
> I don't see any registrations for marscher for live in their directory search.  Did you manage to log in using fu-berlin credentials?   You should have administrative access there and can add another account as an admin or a build admin as needed through it.
I have another email address for my marscher acc on azure/microsoft. I 
wonder why you would need to invite me with my mail address rather than 
my account name. I've checked the settings for something like hiding my 
profile publicly, but haven't found anything.
> 
> I have similar issues with their login system.   When I try to login with github it fails because my account was already tied to my organizations login at Microsoft.   This forces me to have to VPN in to my organization and go through their sign on process.  But once I cached the credentials it appears to go through without that for future.   I just have to go through that procedure when I login in from a new machine.
> 
This is whats happening as soon as I switch to another build when coming 
from the redirection via github, e.g. the current build status of a PR 
I'm allowed to see. For the other builds I get an login screen for the 
Lawrence institute.

**Comment by Thrameos** [comment]
Guess we will have to set up a time to resolve this.   I have poked at all the controls I can see.   There doesn't appear to be any other invite or add mechanism other using their directory search.   

I am not sure why it would give you the Lawrence login unless you were trying to connect to an account with a Lawrence address.  But it is possible that my administrators did their usual and applied super glue to all the controls.   I can't even find the window that I sent out the original invite with.

**Comment by Thrameos** [comment]
Would you mind sending me a direct email to nelson85 at my organization so we can resolve this?  My organization accidentally nuked my WSL installation this morning deleting all my git keys.   Their version of recovery is likely to reimage the machine and pull it the user directory from backup (which may destroy more stuff).  I want to make sure you are an administrator on azure in case they somehow manage blow away even more stuff in the process.

**Comment by Thrameos** [comment]
The log for the failed run is

 ```
  | /.azure/scripts/test.yml (Line: 2, Col: 1): Unexpected value 'variables'722 |  
 ```

It didn't create any logs as far as I can tell because it was a parsing issue.

Because the templates are being pulled as part of a "step"  template they can not include anything but "step" elements.  Thus the variable elements the start of ``test.yml`` have to be pushed back to the ``release.yml`` or the ``build.yml`` at the next top level.  Not sure why this restriction but at least I understand where it is coming from.
 
I tried to trigger this PR manually but instead it wrote a commit to master.   (It was just a trivial change to the CHANGELOG.)  Sorry not sure how to alter an existing PR from another person and get it to trigger the CI properly.   I checked out the PR to a local branch but I can't push back on that PR to make changes.   Likely I am missing a step in the process.  (or it could have something to do with all my keys getting clobbered last night.)

**Comment by marscher** [comment]
Thanks for looking into it. I think with your clue I can fix this myself.

**Comment by Thrameos** [comment]
I think they are restricted to outside the steps area in general.

image

https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch

**Comment by marscher** [comment]
Actually you can push back to forks of the repo, if the PR creator allowed for it (which is the default setting). You just need to checkout the PR locally (e.g. like this: https://stackoverflow.com/questions/27567846/how-can-i-check-out-a-github-pull-request-with-git) and add my repo as a remote in order to push back.

**Comment by marscher** [comment]
now I have the same error as in the sub-run related tests with the newly introduced PyInstaller (which I do not know nothing about). I guess this also uses subprocesses to run stuff and fails for the same reason, as the error message is just the same as before.
```
Traceback (most recent call last):

  File "example.py", line 1, in <module>

  File "C:\hostedtoolcache\windows\Python\3.9.0\x64\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module

    exec(bytecode, module.__dict__)

  File "jpype\__init__.py", line 18, in <module>

ImportError: DLL load failed while importing _jpype: A dynamic link library (DLL) initialization routine failed.
```

**Comment by Thrameos** [comment]
Looks like it is something in the recently contributed PyInstaller test.

```
2020-11-24T20:34:07.5616163Z ##[section]Starting: Test PyInstaller result
2020-11-24T20:34:07.5757964Z ==============================================================================
2020-11-24T20:34:07.5758359Z Task         : Command line
2020-11-24T20:34:07.5758698Z Description  : Run a command line script using Bash on Linux and macOS and cmd.exe on Windows
2020-11-24T20:34:07.5759048Z Version      : 2.177.3
2020-11-24T20:34:07.5759288Z Author       : Microsoft Corporation
2020-11-24T20:34:07.5759632Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/command-line
2020-11-24T20:34:07.5760055Z ==============================================================================
2020-11-24T20:34:08.5213782Z Generating script.
2020-11-24T20:34:08.5616850Z ========================== Starting Command Output ===========================
2020-11-24T20:34:08.5864912Z ##[command]"C:\windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\a\_temp\a2541442-1743-4fb8-aa46-38ca61888e74.cmd""
2020-11-24T20:34:09.0728026Z Processing d:\a\1\s
2020-11-24T20:34:10.9405626Z Using legacy 'setup.py install' for JPype1, since package 'wheel' is not installed.
2020-11-24T20:34:11.0428606Z Installing collected packages: JPype1
2020-11-24T20:34:11.0447189Z     Running setup.py install for JPype1: started
2020-11-24T20:34:13.8853891Z     Running setup.py install for JPype1: finished with status 'done'
2020-11-24T20:34:13.9076944Z Successfully installed JPype1-1.1.3.dev0
2020-11-24T20:34:15.0810983Z pytest C:\hostedtoolcache\windows\Python\3.9.0\x64\lib\site-packages\jpype\_pyinstaller
2020-11-24T20:34:15.0811652Z ============================= test session starts =============================
2020-11-24T20:34:15.0812011Z platform win32 -- Python 3.9.0, pytest-4.6.9, py-1.9.0, pluggy-0.13.1
2020-11-24T20:34:15.0812376Z rootdir: D:\a\1\s\empty
2020-11-24T20:34:15.1418660Z collected 1 item
2020-11-24T20:34:15.1431935Z 
2020-11-24T20:34:44.7361326Z test_jpype_pyinstaller.py F                                              [100%]
2020-11-24T20:34:44.7361999Z 
2020-11-24T20:34:44.7362511Z ================================== FAILURES ===================================
2020-11-24T20:34:44.7363121Z _____________________________ test_start_and_stop _____________________________
2020-11-24T20:34:44.7363481Z 
2020-11-24T20:34:44.7364392Z tmp_path = WindowsPath('C:/Users/VssAdministrator/AppData/Local/Temp/pytest-of-VssAdministrator/pytest-0/test_start_and_stop0')
2020-11-24T20:34:44.7365529Z 
2020-11-24T20:34:44.7366206Z     def test_start_and_stop(tmp_path):
2020-11-24T20:34:44.7366755Z         name = 'e'
2020-11-24T20:34:44.7367325Z         dist = tmp_path.joinpath('dist')
2020-11-24T20:34:44.7367944Z         work = tmp_path.joinpath('build')
2020-11-24T20:34:44.7368524Z         result = dist.joinpath(name, name)
2020-11-24T20:34:44.7369033Z     
2020-11-24T20:34:44.7369510Z         PyInstaller.__main__.run([
2020-11-24T20:34:44.7370010Z             '--name',
2020-11-24T20:34:44.7370510Z             name,
2020-11-24T20:34:44.7370988Z             '--distpath',
2020-11-24T20:34:44.7371513Z             fspath(dist),
2020-11-24T20:34:44.7371997Z             '--workpath',
2020-11-24T20:34:44.7372477Z             fspath(work),
2020-11-24T20:34:44.7373021Z             fspath(example_path),
2020-11-24T20:34:44.7373486Z         ])
2020-11-24T20:34:44.7373871Z     
2020-11-24T20:34:44.7374453Z >       run([fspath(result)], check=True, cwd=fspath(tmp_path))
2020-11-24T20:34:44.7374943Z 
2020-11-24T20:34:44.7376714Z C:\hostedtoolcache\windows\Python\3.9.0\x64\Lib\site-packages\jpype\_pyinstaller\test_jpype_pyinstaller.py:31: 
2020-11-24T20:34:44.7377725Z _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2020-11-24T20:34:44.7378252Z 
2020-11-24T20:34:44.7378502Z input = None, capture_output = False, timeout = None, check = True
2020-11-24T20:34:44.7379192Z popenargs = (['C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_start_and_stop0\\dist\\e\\e'],)
2020-11-24T20:34:44.7380968Z kwargs = {'cwd': 'C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_start_and_stop0'}
2020-11-24T20:34:44.7381565Z process = <Popen: returncode: 4294967295 args: ['C:\\Users\\VssAdministrator\\AppData\...>
2020-11-24T20:34:44.7382002Z stdout = None, stderr = None, retcode = 4294967295
2020-11-24T20:34:44.7382255Z 
2020-11-24T20:34:44.7382520Z     def run(*popenargs,
2020-11-24T20:34:44.7382925Z             input=None, capture_output=False, timeout=None, check=False, **kwargs):
2020-11-24T20:34:44.7383426Z         """Run command with arguments and return a CompletedProcess instance.
2020-11-24T20:34:44.7383808Z     
2020-11-24T20:34:44.7384127Z         The returned instance will have attributes args, returncode, stdout and
2020-11-24T20:34:44.7384561Z         stderr. By default, stdout and stderr are not captured, and those attributes
2020-11-24T20:34:44.7385045Z         will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them.
2020-11-24T20:34:44.7385365Z     
2020-11-24T20:34:44.7385770Z         If check is True and the exit code was non-zero, it raises a
2020-11-24T20:34:44.7386374Z         CalledProcessError. The CalledProcessError object will have the return code
2020-11-24T20:34:44.7386855Z         in the returncode attribute, and output & stderr attributes if those streams
2020-11-24T20:34:44.7387258Z         were captured.
2020-11-24T20:34:44.7387500Z     
2020-11-24T20:34:44.7387837Z         If timeout is given, and the process takes too long, a TimeoutExpired
2020-11-24T20:34:44.7388249Z         exception will be raised.
2020-11-24T20:34:44.7388509Z     
2020-11-24T20:34:44.7388858Z         There is an optional argument "input", allowing you to
2020-11-24T20:34:44.7389300Z         pass bytes or a string to the subprocess's stdin.  If you use this argument
2020-11-24T20:34:44.7389918Z         you may not also use the Popen constructor's "stdin" argument, as
2020-11-24T20:34:44.7390328Z         it will be used internally.
2020-11-24T20:34:44.7390596Z     
2020-11-24T20:34:44.7392448Z         By default, all communication is in bytes, and therefore any "input" should
2020-11-24T20:34:44.7392961Z         be bytes, and the stdout and stderr will be bytes. If in text mode, any
2020-11-24T20:34:44.7393366Z         "input" should be a string, and stdout and stderr will be strings decoded
2020-11-24T20:34:44.7393745Z         according to locale encoding, or by "encoding" if set. Text mode is
2020-11-24T20:34:44.7394082Z         triggered by setting any of text, encoding, errors or universal_newlines.
2020-11-24T20:34:44.7400459Z     
2020-11-24T20:34:44.7400721Z         The other arguments are the same as for the Popen constructor.
2020-11-24T20:34:44.7400944Z         """
2020-11-24T20:34:44.7401123Z         if input is not None:
2020-11-24T20:34:44.7401436Z             if kwargs.get('stdin') is not None:
2020-11-24T20:34:44.7401760Z                 raise ValueError('stdin and input arguments may not both be used.')
2020-11-24T20:34:44.7402235Z             kwargs['stdin'] = PIPE
2020-11-24T20:34:44.7402436Z     
2020-11-24T20:34:44.7402609Z         if capture_output:
2020-11-24T20:34:44.7402961Z             if kwargs.get('stdout') is not None or kwargs.get('stderr') is not None:
2020-11-24T20:34:44.7403378Z                 raise ValueError('stdout and stderr arguments may not be used '
2020-11-24T20:34:44.7403743Z                                  'with capture_output.')
2020-11-24T20:34:44.7403998Z             kwargs['stdout'] = PIPE
2020-11-24T20:34:44.7404224Z             kwargs['stderr'] = PIPE
2020-11-24T20:34:44.7404425Z     
2020-11-24T20:34:44.7404656Z         with Popen(*popenargs, **kwargs) as process:
2020-11-24T20:34:44.7404908Z             try:
2020-11-24T20:34:44.7405215Z                 stdout, stderr = process.communicate(input, timeout=timeout)
2020-11-24T20:34:44.7405752Z             except TimeoutExpired as exc:
2020-11-24T20:34:44.7406001Z                 process.kill()
2020-11-24T20:34:44.7406877Z                 if _mswindows:
2020-11-24T20:34:44.7407208Z                     # Windows accumulates the output in a single blocking
2020-11-24T20:34:44.7407554Z                     # read() call run on child threads, with the timeout
2020-11-24T20:34:44.7407910Z                     # being done in a join() on those threads.  communicate()
2020-11-24T20:34:44.7408297Z                     # _after_ kill() is required to collect that and add it
2020-11-24T20:34:44.7408591Z                     # to the exception.
2020-11-24T20:34:44.7408873Z                     exc.stdout, exc.stderr = process.communicate()
2020-11-24T20:34:44.7409273Z                 else:
2020-11-24T20:34:44.7412947Z                     # POSIX _communicate already populated the output so
2020-11-24T20:34:44.7413300Z                     # far into the TimeoutExpired exception.
2020-11-24T20:34:44.7413628Z                     process.wait()
2020-11-24T20:34:44.7413825Z                 raise
2020-11-24T20:34:44.7414115Z             except:  # Including KeyboardInterrupt, communicate handled that.
2020-11-24T20:34:44.7414440Z                 process.kill()
2020-11-24T20:34:44.7414728Z                 # We don't call process.wait() as .__exit__ does that for us.
2020-11-24T20:34:44.7414990Z                 raise
2020-11-24T20:34:44.7415223Z             retcode = process.poll()
2020-11-24T20:34:44.7415464Z             if check and retcode:
2020-11-24T20:34:44.7415851Z >               raise CalledProcessError(retcode, process.args,
2020-11-24T20:34:44.7416179Z                                          output=stdout, stderr=stderr)
2020-11-24T20:34:44.7416836Z E               subprocess.CalledProcessError: Command '['C:\\Users\\VssAdministrator\\AppData\\Local\\Temp\\pytest-of-VssAdministrator\\pytest-0\\test_start_and_stop0\\dist\\e\\e']' returned non-zero exit status 4294967295.
2020-11-24T20:34:44.7417489Z 
2020-11-24T20:34:44.7417782Z C:\hostedtoolcache\windows\Python\3.9.0\x64\lib\subprocess.py:524: CalledProcessError
2020-11-24T20:34:44.7418289Z ---------------------------- Captured stderr call -----------------------------
```

**Comment by Thrameos** [comment]
Okay I will try to take a look at it using a M$ installation that I have on my machine.   I will have to get it up to date for Python 3.9.   But we are very close.   Thanks for pushing this forward.

**Comment by marscher** [comment]
I think we should investigate, why this import fails for Python-3.9. I guess it is some kind of name clash (static global variables) and the dll is already loaded and shared in memory... just wondering why this would only happen for Python-3.9, as this version uses the same container (e.g. win version) as the other snakes

**Comment by Thrameos** [comment]
It could be a change in the lookup rules or some configuration variable when Python got built.   I have had weird problems with things like trying to resolve jpype/types.py from system/types.py.   Python doesn't have very ridged walls between things so sometimes some very incent looking configuration or file will cause unexpected issues.   

That said debugging anything on the CI is always 10 times harder than local.   So if I can reproduce it locally then we can resolve it easily.

**Comment by marscher** [comment]
Reproducing it should be as easy as conda create -n py39_jpype python=3.9 and compiling jpype in in, right? Luckily I do not possess a windows machine any more :)

**Comment by marscher** [comment]
sorry for being out of sync, I'd have expected Github to update asynchronicity (that would be to modern, right?)

**Comment by Thrameos** [comment]
Wow I had remarkably little luck building on windows for Python3.9.

Python 3.8 works fine under conda, but both 3.9 under conda and with a generic install both give.

```
  File "C:\Users\nelson85\Documents\devel\open\jpype\test2.py", line 1, in <module>
    import jpype
  File "C:\Users\nelson85\Documents\devel\open\jpype\jpype\__init__.py", line 18, in <module>
    import _jpype
ImportError: DLL load failed while importing _jpype: A dynamic link library (DLL) initialization routine failed.
```

Unfortunately this is the least helpful error you can get.   Some imported symbol is not being found and thus causing it to crash.  But since it won't tell me which symbol failed it just leaves one to make random guesses.

**Comment by Thrameos** [comment]
I am going to have to give this one up for the night.   I did a comparison of the library symbols and found no issue.   So then I did a scan for differences in the compilation.   As far as I can tell the main difference is that building with 3.8 uses quotes around the options to the compiler and 3.9 does not.  Though looking at the symbols I can't see how this would have had any effect whatsoever.

**Comment by Thrameos** [comment]
This appears to be above my pay grade.   I uninstalled everything, built on 3.9, run the tests (everything passes), then I ran the test a second time.  I get the dreaded "initialization routine failed".   I then delete the ``__pycache__`` everything works, run it a second time all fails.

This appears to be a Python bug where in it fails to load the `_jpype` module when loaded from the cache directory.   It is possible that we are improperly loading our module or something in the setup procedure for modules has changed, but it is way outside of my understanding.

This would definitely explain weird failures in the CI system if the cache file gets busted.   When we run from the CI the first time everything would be fine, but any subshells would likely get the corrupt copy and fail.   

@marscher  You got the name of a Python core developer who can shed some insight as there is no way I am going to solve this one on my own?   :sob:

**Comment by Thrameos** [comment]
I gave one last shot at it....  Using hacking magic I have decompiled the pyc under 3.6 and 3.9 versions.  

Both give...
```
18           0 LOAD_CONST               0 (0)
              2 LOAD_CONST               1 (None)
              4 IMPORT_NAME              0 (_jpype)
              6 STORE_NAME               0 (_jpype)
```

So it is not a problem in the byte code but with Python 3.9 itself.   I have no reason to suspect it is not confined to Windows at the current time, but definitely a bug outside of our scope.

**Comment by Thrameos** [comment]
@marscher  Okay it is turkey day and I was going to start our release cycle.   I believe we have enough for 1.2 but Py3.9 on windows is clearly broken.   I am going to apply this PR and then remove the offending windows so we can deal with it later.
Sounds good?

**Pull request merged**
