### PR TITLE
4-byte utf8 test case added

### PR DESCRIPTION
**Pull request by rene-bakker-it**
Added a Java test class jpype.utf8.Utf8Test and a corresponding python unit test utf8.py to the repository. 

Currently the tests fails as described in issue #278 (Incorrect pasing of 4-byte utf-8 characters from python3 to java, and vice-versa). Details are mentioned in the header of the python fiie.

It is intended for tests of the 0.7.0 RC.

### CODE REVIEW

**Comment by Thrameos** [comment]
Excellent.  I applied it to devel.  Currently failing on ant part.

```
compile:
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\build.xml:15: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 4 source files to C:\cygwin64\home\nelson85\devel\open\jpype\test\classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:8: error: unmappable character for encoding Cp1252
    [javac]             "ᛖᚴ ᚷᛖ▒? ᛖ▒?▒? ᚧ ᚷᛚᛖᚱ ᛘᚾ ᚦᛖᛋᛋ ᚨᚧ ᚡᛖ ᚱᚧᚨ ᛋᚨᚱ",
    [javac]                             ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:8: error: unmappable character for encoding Cp1252
    [javac]             "ᛖᚴ ᚷᛖ▒? ᛖ▒?▒? ᚧ ᚷᛚᛖᚱ ᛘᚾ ᚦᛖᛋᛋ ᚨᚧ ᚡᛖ ᚱᚧᚨ ᛋᚨᚱ",
    [javac]                                    ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:8: error: unmappable character for encoding Cp1252
    [javac]             "ᛖᚴ ᚷᛖ▒? ᛖ▒?▒? ᚧ ᚷᛚᛖᚱ ᛘᚾ ᚦᛖᛋᛋ ᚨᚧ ᚡᛖ ᚱᚧᚨ ᛋᚨᚱ",
    [javac]                                       ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:9: error: unmappable character for encoding Cp1252
    [javac]             "人人生而自由,在尊严和▒?▒利上一律平等。他们赋有▒?▒性和良心,并应以兄弟关系的精神互相对待。",
    [javac]                                              ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:9: error: unmappable character for encoding Cp1252
    [javac]             "人人生而自由,在尊严和▒?▒利上一律平等。他们赋有▒?▒性和良心,并应以兄弟关系的精神互相对待。",
    [javac]                                                                                  ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:10: error: unmappable character for encoding Cp1252
    [javac]             "人人生而自由▒?在尊嚴和權利上一律平等。他們賦有▒?▒性和良心▒?並應以兄弟關係的精神互相▒?待。",
    [javac]                                  ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:10: error: unmappable character for encoding Cp1252
    [javac]             "人人生而自由▒?在尊嚴和權利上一律平等。他們賦有▒?▒性和良心▒?並應以兄弟關係的精神互相▒?待。",
    [javac]                                                                                    ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:10: error: unmappable character for encoding Cp1252
    [javac]             "人人生而自由▒?在尊嚴和權利上一律平等。他們賦有▒?▒性和良心▒?並應以兄弟關係的精神互相▒?待。",
    [javac]                                                                                                    ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:10: error: unmappable character for encoding Cp1252
    [javac]             "人人生而自由▒?在尊嚴和權利上一律平等。他們賦有▒?▒性和良心▒?並應以兄弟關係的精神互相▒?待。",
    [javac]                                                                                                                                           ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:12: error: unmappable character for encoding Cp1252
    [javac]             "▒?😂😃😄😅😆😠😡😢😣😤😥😨😩😪🚉🚌▒?🚑🚒🚓🚕🚗🚙🚚🚢🚤🚥🚧🚨🚻🚼🚽🚾🛀🆕🆖🆗🆘🆙🆚▒?🈂🈚🈯🈹🈺▒?🉑8⃣9⃣7⃣6⃣1⃣0"
    [javac]                 ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:12: error: unmappable character for encoding Cp1252
    [javac]             "▒?😂😃😄😅😆😠😡😢😣😤😥😨😩😪🚉🚌▒?🚑🚒🚓🚕🚗🚙🚚🚢🚤🚥🚧🚨🚻🚼🚽🚾🛀🆕🆖🆗🆘🆙🆚▒?🈂🈚🈯🈹🈺▒?🉑8⃣9⃣7⃣6⃣1⃣0"
    [javac]                                                                                     ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:12: error: unmappable character for encoding Cp1252
    [javac]             "▒?😂😃😄😅😆😠😡😢😣😤😥😨😩😪🚉🚌▒?🚑🚒🚓🚕🚗🚙🚚🚢🚤🚥🚧🚨🚻🚼🚽🚾🛀🆕🆖🆗🆘🆙🆚▒?🈂🈚🈯🈹🈺▒?🉑8⃣9⃣7⃣6⃣1⃣0"
    [javac]                                                                                                                                                                                     ^
    [javac] C:\cygwin64\home\nelson85\devel\open\jpype\test\harness\jpype\utf8\Utf8Test.java:12: error: unmappable character for encoding Cp1252
    [javac]             "▒?😂😃😄😅😆😠😡😢😣😤😥😨😩😪🚉🚌▒?🚑🚒🚓🚕🚗🚙🚚🚢🚤🚥🚧🚨🚻🚼🚽🚾🛀🆕🆖🆗🆘🆙🆚▒?🈂🈚🈯🈹🈺▒?🉑8⃣9⃣7⃣6⃣1⃣0"
    [javac]                                                                                                                                                                                                             ^
    [javac] 13 errors
    [javac] 1 warning
```

I am guessing that I will need to escape all the chars so that editors and system text conversion settings don't interfere with the test.  No action required on your part.

**Comment by Thrameos** [comment]
Okay it is now runnable.

2 passes.
3 fails because the conversion from "bytes" to "byte[]" is not implemented.
2 fails because java.lang.String has to be converted using "str()" or "unicode()".  Automatic conversions were forcing it to guess resulting in some random behavior.  
1 mystery fail.

I should be about to correct those fails pretty easy with this test bench.  Thanks for you hard work.

``` .EEE.FFE
======================================================================
ERROR: Test binary upload and check in Java if the strings are correct.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nelson85/devel/open/jpype/test/jpypetest/utf8.py", line 116, in test_binary_upload
    utf8_test = self.Utf8Test(String(val.encode(), 'UTF8'))
  File "/home/nelson85/devel/open/jpype/jpype/_jobject.py", line 79, in __init__
    jv = self.__class__.__javaclass__.newInstance(*args)
RuntimeError: No matching overloads found for constructor java.lang.String(bytes,str), options are:
        public java.lang.String(byte[],int,int,int)
        public java.lang.String(byte[],int)
        public java.lang.String(char[],int,int)
        public java.lang.String(java.lang.String)
        public java.lang.String(char[])
        public java.lang.String()
        public java.lang.String(int[],int,int)
        public java.lang.String(byte[])
        public java.lang.String(java.lang.StringBuffer)
        public java.lang.String(java.lang.StringBuilder)
        public java.lang.String(byte[],int,int,java.lang.String) throws java.io.UnsupportedEncodingException
        public java.lang.String(byte[],int,int,java.nio.charset.Charset)
        public java.lang.String(byte[],java.lang.String) throws java.io.UnsupportedEncodingException
        public java.lang.String(byte[],java.nio.charset.Charset)
        public java.lang.String(byte[],int,int)

        at findOverload(native/common/jp_method.cpp:247)
        at findOverload(native/common/jp_method.cpp:250)
        at newInstance(native/common/jp_stringclass.cpp:120)
        at newInstance(native/python/pyjp_class.cpp:278)


======================================================================
ERROR: Test pure binary upload and download of utf strings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nelson85/devel/open/jpype/test/jpypetest/utf8.py", line 142, in test_binary_upload_no_surrogates
    utf8_test = self.Utf8Test(String(val.encode(), 'UTF8'))
  File "/home/nelson85/devel/open/jpype/jpype/_jobject.py", line 79, in __init__
    jv = self.__class__.__javaclass__.newInstance(*args)
RuntimeError: No matching overloads found for constructor java.lang.String(bytes,str), options are:
        public java.lang.String(byte[],int,int,int)
        public java.lang.String(byte[],int)
        public java.lang.String(char[],int,int)
        public java.lang.String(java.lang.String)
        public java.lang.String(char[])
        public java.lang.String()
        public java.lang.String(int[],int,int)
        public java.lang.String(byte[])
        public java.lang.String(java.lang.StringBuffer)
        public java.lang.String(java.lang.StringBuilder)
        public java.lang.String(byte[],int,int,java.lang.String) throws java.io.UnsupportedEncodingException
        public java.lang.String(byte[],int,int,java.nio.charset.Charset)
        public java.lang.String(byte[],java.lang.String) throws java.io.UnsupportedEncodingException
        public java.lang.String(byte[],java.nio.charset.Charset)
        public java.lang.String(byte[],int,int)

        at findOverload(native/common/jp_method.cpp:247)
        at findOverload(native/common/jp_method.cpp:250)
        at newInstance(native/common/jp_stringclass.cpp:120)
        at newInstance(native/python/pyjp_class.cpp:278)


======================================================================
ERROR: Test binary upload and download of utf strings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nelson85/devel/open/jpype/test/jpypetest/utf8.py", line 128, in test_binary_upload_with_surrogates
    utf8_test = self.Utf8Test(String(val.encode(), 'UTF8'))
  File "/home/nelson85/devel/open/jpype/jpype/_jobject.py", line 79, in __init__
    jv = self.__class__.__javaclass__.newInstance(*args)
RuntimeError: No matching overloads found for constructor java.lang.String(bytes,str), options are:
        public java.lang.String(byte[],int,int,int)
        public java.lang.String(byte[],int)
        public java.lang.String(char[],int,int)
        public java.lang.String(java.lang.String)
        public java.lang.String(char[])
        public java.lang.String()
        public java.lang.String(int[],int,int)
        public java.lang.String(byte[])
        public java.lang.String(java.lang.StringBuffer)
        public java.lang.String(java.lang.StringBuilder)
        public java.lang.String(byte[],int,int,java.lang.String) throws java.io.UnsupportedEncodingException
        public java.lang.String(byte[],int,int,java.nio.charset.Charset)
        public java.lang.String(byte[],java.lang.String) throws java.io.UnsupportedEncodingException
        public java.lang.String(byte[],java.nio.charset.Charset)
        public java.lang.String(byte[],int,int)

        at findOverload(native/common/jp_method.cpp:247)
        at findOverload(native/common/jp_method.cpp:250)
        at newInstance(native/common/jp_stringclass.cpp:120)
        at newInstance(native/python/pyjp_class.cpp:278)


======================================================================
ERROR: Test python string upload and download of utf strings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nelson85/devel/open/jpype/test/jpypetest/utf8.py", line 164, in test_string_upload_with_surrogates
    rval = utf8_test.get().encode('utf-16').decode('utf-16')
AttributeError: 'java.lang.String' object has no attribute 'encode'

======================================================================
FAIL: Test binary upload and check in Java if the strings are correct.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nelson85/devel/open/jpype/test/jpypetest/utf8.py", line 153, in test_string_upload
    self.assertTrue(utf8_test.equalsTo(indx), "Utf8Test.java binary upload: indx %d = %s" % (indx, lbl))
AssertionError: False is not true : Utf8Test.java binary upload: indx 2 = rune

======================================================================
FAIL: Test pure python string upload and download of utf strings.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nelson85/devel/open/jpype/test/jpypetest/utf8.py", line 176, in test_string_upload_no_surrogates
    self.assertEqual(val, utf8_test.get(), "Utf8Test.java string upload for: " + lbl)
AssertionError: 'Je peux manger du verre, ça ne me fait pas mal.' != <jpype._jclass.java.lang.String object at 0x6fffe9dce48> : Utf8Test.java string upload for: french

----------------------------------------------------------------------
Ran 8 tests in 0.693s

FAILED (errors=4, failures=2)
```

**Comment by Thrameos** [comment]
So I have four tasks to complete before this can pass on devel.
- [ ] Implement `bytes` to `byte[]` for Python3
- [ ] Implement `str` to `byte[]` for Python2
- [ ] Implement `__unicode__` for Python2
- [ ] Update the tests to use conversion `str()` and `unicode()` where appropriate.

Then I will need the CI system back up and the review of devel branch completed so that we know that this will work across all platforms.

**Comment by Thrameos** [comment]
Don't worry I can resolve it.  The particular problem was likely with code point counting error.  There are a lot of methods that report a size, some in bytes and some in codepoints.  Unfortunately, I probably picked the wrong one.  I just have to add a call to the test harness to print the string that came in.  That way I can figure out if it was the java to python converter or the python to java converter that has the bug.  It is also possible it is a problem with my zero termination code.  It is surprising that if failed on French because I would assume anything that messes up there would mess up in ascii strings.

I did have to make a few minor changes to the tests.  Under devel code it does not directly return a python string but rather java.lang.String object.  I then call `str` or `unicode` as appropriate for the flavor of Python to force the conversion.  java.lang.String is overloaded such that most calls work fine but equals seems to have some order dependence because `java.lang.String("foo") == str("foo")` works, but `str("foo") == java.lang.String("foo")`.  If you need to access a python method then it is necessary to insert a conversion  call like you see below.  I tried the method of deriving java.lang.String from python str, but it was a real mess because we have both 'startswith' and 'startsWith', etc.  

```
        try:
            rval = str(utf8_test.get()).encode('utf-16').decode('utf-16')
        except UnicodeEncodeError as uue:
            rval = str(utf8_test.get()).encode('utf-16', errors='surrogatepass').decode('utf-16')
```

The hardest one that I am likely to face is embedded null characters.  The current call that I am using to create the strings assumes zero terminated.  That means embedded null has to be reencoded into java null indicators so I don't end up terminating the string.  I will have to add some test cases for those as well.

**Comment by Thrameos** [comment]
Made some progress.  The bug was as I suspected that java was counting code points and I needed the length in bytes.   Replaced the faulty call with `GetStringUTFLength`. Now everything works for French.  

Next sticking point is runes.  For some reason that is getting length 0 strings pushed to java.   So some more investigation required.   Chinese and emoji have the same issue so it is likely a common problem in unpacking the python strings to the jpype utf transcriber function.

**Comment by Thrameos** [comment]
This is now completed on the devel_utf8 branch.

**Comment by Thrameos** [comment]
Python 2 now works as well in devel_utf8 branch.   Thanks for your contribution.   We will need to wait until the 0.7.0 is pulled to the head, rebase this pull request, then I can merge it if you want the line contribution in the project.

**Comment by marscher** [comment]
@Thrameos you know you can fork forks? ;) This way we can keep contributions. Sorry @rene-bakker-it I just merged the follow up PR first and did not see, I should have merged this one before.

**Comment by Thrameos** [comment]
Yeah I attempted to fork the fork, but when I did a rebase/squash, it all got turning into mush.

**Pull request closed without merging**
