### PR TITLE
Cycle

### LINKED ISSUE #1034: Release 1.3.1
- [x] Start from the release branch
      ``git checkout release``
- [x] Make a new branch for the release cycle
      ``git checkout -b releases/{version}``
- [x] Merge the current master with the release
      ``git pull origin master``
- [x] Start a release
      ``bumpversion release``
- [x] Edit doc/CHANGELOG.rst
- [x] Send the release to be evaluated
      ``git push``
- [x] Verify CI on azure
- [x] Manually trigger a ``jpype.release`` on azure
      If successful, download the artifacts for publication.
- [x] Advance the release pointer
      ``git checkout release``
      ``git merge releases/<version>``
- [x] Publish the release
  - Add draft release on github
  - Attach the artifacts to the release.
- [x] Start master on a new cycle
  - Use a PR to pull release back to master
  - ``git checkout master``
  - ``git checkout -b cycle``
  - ``git merge release``
  - ``bumpversion patch``
  - Use PR to insert the cycle in master

### PR DESCRIPTION
**Pull request by Thrameos**
Changes required to release v1.4.0.

Unfortunately after many hours I still can't get the Python-3.10 on osx-11 to work.  But I can't really hold up everything else for the one wheel.   Will try again when I next get an opening.

Fixes #1034

### CODE REVIEW

**Review by marscher — APPROVED** [review]

**Comment by marscher** [comment]
Thanks a lot for all your work on this. What is the problem with OSX?

**Comment by marscher** [comment]
looks like the url to the osx python installer is just wrong, try using this one: https://www.python.org/ftp/python/3.10.4/python-3.10.4-macos11.pkg

**Comment by Thrameos** [comment]
I see they dropped the x and I didn't notice it.  I will give it another shot.

**Comment by Thrameos** [comment]
The wheel came out oddly named on macos11.  Not sure why but hopefully it works.    I guess we just push the wheels and hope for the best.

**Comment by pelson** [comment]
> I guess we just push the wheels and hope for the best.

They haven't yet been pushed to pypi fwiw: https://pypi.org/project/JPype1/#history

(also mentioned in https://github.com/jpype-project/jpype/issues/1028#issuecomment-1130587686)

**Comment by marscher** [comment]
Sorry, I forgot to do that. Will do when I'm back home.

**Comment by marscher** [comment]
Unfortunately I cannot get the pypi api tokens to work. I need to figure out why, when I have more time...
Again sorry for the delay.

**Comment by marscher** [comment]
got it.

**Pull request merged**
