### PR TITLE
Annotations

### PR DESCRIPTION
**Pull request by Thrameos**
This is a test pull for annotations.  Thus far I haven't seen any change in behavior.  Please do not merge this one until we confirm function.

### CODE REVIEW

**Comment by Thrameos** [comment]
This one is getting closer to ready.  Although it is not possible to get tab completion to work as was request, I did manage to get 95% of the Python function API working.  I also found a difficult to hit segmentation fault.  So despite being a failure I was able to get something good out of it.

**Comment by Thrameos** [comment]
The kind author of Jedi did an update that should correct our issue with signatures for Python3.   Hopefully in combination with this pull request we wall actually have working tab completion.  This latest commit converts our PyJPMethod to be a FunctionType for the purposes of Python2 and Python3.  Though this is good because we now don't require special treatment in places that are probing the object, it also may have some unexpected side effects.  I am debating if I should rename the object type for PyJPField and PyJPMethod to JField and JMethod, and create an alias in ``jpype``.  Unlike the rest of ``_jpype`` types these are directly exposed to the users.

**Comment by Thrameos** [comment]
Some jedi patterns are completing properly now with unreleased version 0.14.1 but others are still failing.  Thus I put another ticket in with jedi.

**Comment by Thrameos** [comment]
Well it was a very long road but we now support docstrings and annotations.  This requires jedi version 0.14.1 which is unreleased but on my modified copy I get successful completions of classes, methods and fields. 

@marscher This is now ready for review for version 0.7.1.

**Comment by marscher** [comment]
Shall we include this for 0.7 or really wait for a patch release?

**Comment by Thrameos** [comment]
Lets keep this one for now.  I think that it is all good, but I have not given it a good beating.  The FunctionType has a flag for VectorOperations that I do not yet understand the implications of.  Thus I suspect that there is a path that will cause problems.  I just don't know how to hit it.

**Comment by Thrameos** [comment]
@marscher Any chance for this to get reviewed or should I self review to get us up to a release candidate?

**Pull request merged**
