### PR TITLE
fixes #1242

### LINKED ISSUE #1242: Failure to start JVM with jpype 1.5.1 on Windows
With 1.5.0 on this env I could start the JVM.
```
C:\Users\alexandre.villares>python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpype
>>> jpype.__version__
'1.5.0'
>>> jpype.startJVM()
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
>>> jpype.getDefaultJVMPath()
'C:\\Users\\alexandre.villares\\Downloads\\thonny-4.1.6-portable\\user_data\\jdk-17\\bin\\server\\jvm.dll'
>>>
```
Updating to jpype 1.5.1 it fails:
```
C:\Users\alexandre.villares>python -m pip install jpype1 --upgrade
Requirement already satisfied: jpype1 in c:\users\alexandre.villares\downloads\thonny-4.1.6-portable\lib\site-packages (1.5.0)
Collecting jpype1
  Downloading jpype1-1.5.1-cp310-cp310-win_amd64.whl.metadata (5.0 kB)
Requirement already satisfied: packaging in c:\users\alexandre.villares\downloads\thonny-4.1.6-portable\lib\site-packages (from jpype1) (24.2)
Downloading jpype1-1.5.1-cp310-cp310-win_amd64.whl (356 kB)
Installing collected packages: jpype1
  Attempting uninstall: jpype1
    Found existing installation: JPype1 1.5.0
    Uninstalling JPype1-1.5.0:
      Successfully uninstalled JPype1-1.5.0
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\alexandre.villares\AppData\Local\Temp\pip-uninstall-lxb7b830'.
  You can safely remove it manually.
Successfully installed jpype1-1.5.1

C:\Users\alexandre.villares>python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpype
>>> jpype.__version__
'1.5.1'
>>> jpype.startJVM()
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
Error occurred during initialization of VM
Could not find agent library instrument on the library path, with error: Can't find dependent libraries
Module java.instrument may be missing from runtime image.

C:\Users\alexandre.villares>python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import jpype
>>> jpype.getDefaultJVMPath()
'C:\\Users\\alexandre.villares\\Downloads\\thonny-4.1.6-portable\\user_data\\jdk-17\\bin\\server\\jvm.dll'
>>>
```

### PR DESCRIPTION
**Pull request by astrelsky**
I don't know what to say other then, no this was not a security issue and no this doesn't introduce one.

fixes #1242

### CODE REVIEW

**Comment by astrelsky** [comment]
@Thrameos I need a nap cause I can't think but I did confirm this was the problem. There could be "seciruty" arguments about this but I think they're all bullshit.

**Comment by astrelsky** [comment]
`ValueError: Unable to get JVM bin path from C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\11.0.25-9\x64\bin\client\jvm.dll`

Stupid me forgot about std::wstring, that'll make this easier.

**Comment by Thrameos** [comment]
I am having a hard time fathoming how we could ever be in a situation where the JVM loaded itself using another versions dll.  This seems extraordinarily broken.   Is there any chance of this on the linux version?

**Comment by ryanmkurtz** [comment]
Is anything new calling just "java" vs using JAVA_HOME?

**Comment by astrelsky** [comment]
> I am having a hard time fathoming how we could ever be in a situation where the JVM loaded itself using another versions dll.  This seems extraordinarily broken.   Is there any chance of this on the linux version? 

I watched it happen in the debugger and can show you the logs if necessary.

**Comment by astrelsky** [comment]
> Is anything new calling just "java" vs using JAVA_HOME?

No.

**Comment by astrelsky** [comment]
> I am having a hard time fathoming how we could ever be in a situation where the JVM loaded itself using another versions dll.  This seems extraordinarily broken.   Is there any chance of this on the linux version? 

The easiest way to check if it occurs on Linux would be to get the zip file of the jdk, extract it somewhere and then without adding it to PATH, specify the absolute path to the jvm.so in `startJVM` and then check the paths of all the currently loaded libraries. I don't know how you would get the paths of the currently loaded libraries on Linux though.

**Pull request closed without merging**
