### PR TITLE
Document onJVMStart

### LINKED ISSUE #938: JPype onJVMStart not documented
I learnt about ``jpype.onJVMStart`` through one of our issue threads, and realised I'd never seen it mentioned before. It doesn't seem to be a documented API. Can we add it to the built docs?

### PR DESCRIPTION
**Pull request by Thrameos**
Fixes #938

### CODE REVIEW

**Review by marscher — APPROVED** [review]
LGTM

**Comment by pelson** [comment]
I was looking for the change at https://jpype.readthedocs.io/en/latest/api.html, but it doesn't have ``onJVMStart`` documented.

The [source of the docs (when I go to view source in the browser)](https://jpype.readthedocs.io/en/latest/api.html) shows that the build is for commit 46a55ba7, which is this commit, so I don't think this is actually doing the right thing.


When I build the docs locally it works as expected though. :thinking: 

Looks like a RTD issue rather than anything here.

**Comment by Thrameos** [comment]
Not sure on this one.  Most likely it is a RTD version issue.  RTD uses specific versions of sphinx and related tools.  Autodecator must not be in that version.  We could make it autofunction or look to see if this is something controllable.  But most stuff on RTD is pretty much superglued to prevent explotation.

**Comment by Thrameos** [comment]
@marscher i am a bit confused about the doc requirements.  We have 3 files with doc requirements in the project: doc/requirements.txt, doc/doc-requirements.txt and doc-requirements.txt.  rtd is pointing to an empty one.  Also we have a lot of pinned versions, but sphinx itself doesn't have a required version which may be why we get an old version.   Any preferences on how to clean this up?

**Pull request merged**
