### PR TITLE
Improved exception stacktraces

### PR DESCRIPTION
**Pull request by Thrameos**
This is an attempt to integrate Java stacktrace into Python traceback system to create seamless error reporting thus negating the need for stacktrace() to be called to extract the error information.  The pull request is to test functionality in the test matrix.

### CODE REVIEW

**Comment by Thrameos** [comment]
The remaining work on this is just to add #if over sections so that symbols that aren't in each of the versions.  I will update it when I get back from vacation.

**Comment by Thrameos** [comment]
I think this is ready for review.  This pull request integrates the Java and Python exception systems so that Java exceptions appear as native Python exceptions.  

This required a lot more effort that I hoped.  Many elements of the Python exception system require access to private or unextendable resources.  It may be a good idea to try to get better support in Python for this, but for now this will have to do.

**Comment by Thrameos** [comment]
This one has gone stale and will require a fair amount of work to pull forward.

**Comment by Thrameos** [comment]
@marscher This one is freshened and ready to go.  Ignore the missing "ant" on macos, it appears to be a CI bletch.  Once we have these resolved I can move on to merging the head back into development so we can move forward to classhints and its big speed improvement.

**Comment by Thrameos** [comment]
This one is back to the drawing board until I can remerge it with master.

**Comment by Thrameos** [comment]
@marscher back alive and ready for review.  This pull request hacks the Python error reporting system to attach Java exception information as the "cause" of an exception thrown from Java or C++ so that we don't need a special stacktrace() command or produce long exception messages with "at... at...".

```
Traceback (most recent call last):
  File "ExceptionTest.java", line 57, in jpype.exc.ExceptionTest.throwChain
  File "ExceptionTest.java", line 62, in jpype.exc.ExceptionTest.method1
  File "ExceptionTest.java", line 67, in jpype.exc.ExceptionTest.method2
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    cls.throwChain()
jpype._jclass.RuntimeException: java.lang.RuntimeException: Inner
``

There was a bit of wizardary here as Python doesn't let one directly mock a stacktrace that is usuable with native methods because they directly access internal fields so the method tb_create in jp_exception.cpp replicates creating the structures used internally in Python.  It requires the Java code be compiled with "lines" as the debugging flag if accurate lines are to be reported on the trace (otherwise we just get -1).   

I am slightly worried about the long term stability on this because of the level of structure hacking involved.  I couldn't attract any attention from the Python devs on the forums I posted on (for this or other internals questions) so this likely the best I can do.  Until they add a "make exception from a list of stack info" in the API we will have to hack it.

**Comment by marscher** [comment]
I share your concern about long term stability. The CPython looks tricky. Maybe there is a good reason for the separated stacktrace generation functionality in the first place. If you think the benefits of this outrun the additional future overhead, I'd be to merge this.

**Comment by Thrameos** [comment]
I believe @KOLANICH can speak best to this (see #523).  The problem is specifically that a default unhandled exception goes to the default Python printer which is not aware of the Java stack trace so it prints just the Python portion.  Thus ever piece of code ends up looking like.

```
try:
    ... bunch of code...
catch JException as ex:
   print(ex.stacktrace())
   throw ex
```

Secondarily the C++ portion of the exception is being attached to the message so rather than getting "Exception here",  we get "Exception here
   at  fred
   at  george
   at bob"

Thus we have two very different things both of which are not very Pythonic.   The problem being we really need some input from a CPython core developer to give use some direction on how to implement this Pythonically.  I am fine with this hack solution for now if they plan give a "PyErr_AddCauseWithStackTrace(PyObject* Exception, PyObject *StackFrameList)" at some point in the future that I can then remove this code.   At least when I worked in Gnome had an IRC channel and they monitored the SVN commit log on email I could get input if needed.

**Comment by marscher** [comment]
I can see the improvements of better error messages. One question remains, what happens, when people still call ex.stacktrace() in their codes?

**Comment by Thrameos** [comment]
Stacktrace() still contains the Java stacktrace just like before.  There is no change to existing code.   Instead if you do not handle a JException different than a Python exception you will get the stacktrace information as the “cause”.   This of course only works because we have dropped Python 2 where cause was not supported.  Thus if the code caught JException first and calls print(ex.stacktrace())  they get the stacktrace (in the expected Java order inner to outer).  If they do not handle the exception or call the Python methods for printing the stacktrace, they get the Python portion of the stacktrace proceeded by the C++ or Java in a fake exception with the exception information order Pythonically from outer to inner.

Once I get Java tied back into the Python system (work in progress), then if a Proxy throws in Python, you get a set of exceptions( Python caused… Java caused… Python caused).  If gets a bit tricky if a Java exception is thrown in a Proxy as Java exception will have a cause the skips over the Python portion, but otherwise it should be pretty smooth.

The only thing this pull request drops is the “…at foo.cpp:1\n...at bar.cpp:2”  from being attached to the message when an internal error happens in JPype.  But that information was primarily for reporting bugs to the project and not for the user.  Thus attaching it as the cause instead should be better.

**Pull request merged**
