### PR TITLE
[ci] allow to download missing Python versions

### PR DESCRIPTION
**Pull request by marscher**

### CODE REVIEW

**Comment by marscher** [comment]
@Thrameos it seems I do not have the permission on Azure to add a Github action token since I cannot access any settings on Azure. Would you please either give me permissions or add a token yourself?

**Comment by Thrameos** [comment]
Sure I can give it a try.

**Comment by Thrameos** [comment]
I think I managed to promote you to a project-admin or perhaps some random person.  Please give it another try.   

If not use my contact card to send me a direct email with the details of what needs to be done.

**Comment by Thrameos** [comment]
Is everything working now? I am overdue to start a release.  Is there any PR that should be included?

**Pull request merged**
